resource_types:
  - name: slack-notification
    type: docker-image
    source:
      repository: cfcommunity/slack-notification-resource
      tag: latest

resources:
  - name: source
    type: git
    source:
      uri: ((source_repository_url))
      branch: ((source_repository_branch))
      private_key: ((git_ssh_key))

  - name: node-builder-image
    type: docker-image
    source:
      repository: ((node_builder_image_repository_url))
      aws_access_key_id: ((aws_access_key_id))
      aws_secret_access_key: ((aws_secret_access_key))

  - name: notify-success
    type: slack-notification
    source:
      url: ((slack_builds_webhook_url))

  - name: notify-failure
    type: slack-notification
    source:
      url: ((slack_engineering_webhook_url))

groups:
  - name: development-cadmium
    jobs:
      - provision-development-cadmium-website
      - provision-development-cadmium-content
#  - name: production-sulfur
#    jobs:
#      - provision-production-sulfur-website
#      - provision-production-sulfur-content

jobs:
  - name: provision-development-cadmium-website
    serial: true
    plan:
      - in_parallel:
          - get: source
            trigger: true
          - get: node-builder-image
      - task: build
        image: node-builder-image
        file: source/pipelines/main/provision-website/task.yaml
        params:
          GPG_KEY: ((gpg_key))
          PROVISIONING_ROLE_ARN: ((development_cadmium_provisioning_role_arn))
          DEPLOYMENT_TYPE: ((development_cadmium_deployment_type))
          DEPLOYMENT_LABEL: ((development_cadmium_deployment_label))

    on_success: &on_success
      put: notify-success
      params:
        text: ((slack_success_message))
        channel: ((slack_success_channel))

    on_failure: &on_failure
      put: notify-failure
      params:
        text: ((slack_failure_message))
        channel: ((slack_failure_channel))

    on_error: &on_error
      put: notify-failure
      params:
        text: ((slack_error_message))
        channel: ((slack_error_channel))

    on_abort: &on_abort
      put: notify-failure
      params:
        text: ((slack_abort_message))
        channel: ((slack_abort_channel))

  - name: provision-development-cadmium-content
    plan:
      - in_parallel:
          - get: source
            trigger: true
            passed:
              - provision-development-cadmium-website
          - get: node-builder-image
      - task: test
        image: node-builder-image
        file: source/pipelines/main/provision-content/task.yaml
        params:
          GPG_KEY: ((gpg_key))
          PROVISIONING_ROLE_ARN: ((development_cadmium_provisioning_role_arn))
          DEPLOYMENT_TYPE: ((development_cadmium_deployment_type))
          DEPLOYMENT_LABEL: ((development_cadmium_deployment_label))

    on_success: *on_success
    on_failure: *on_failure
    on_error: *on_error
    on_abort: *on_abort
